version: 2

sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
      - name: orders

  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment

  - name: customers
    database: TEST1
    schema: DBT_SAIROHIT0917
    tables:
      - name: stg_customer_address